### ISSUE TITLE
USER STORY: Wireframes

### ISSUE THREAD

**Issue by JodyMurray** [Edmir-Demaj/hackathon-june-23#7]
As an **Admin**, I want to **create a wireframe for this project**, so that I **work towards the same goal with my teammates**

Tasks:

* [x] - Create Wireframe using Figma or Balsimiq.
* [x] - Display discussed features.
* [x] - Post wireframe in group chat for discussion.

**Comment by ignasvilkas** [comment]
Done as long as everybody is happy with the wireframes
